import React, { useState } from 'react';
import { dataLogger } from '../services/dataLogger';
import { DataLogEntry } from '../types';

interface DataExportProps {
  onClose: () => void;
}

const DataExport: React.FC<DataExportProps> = ({ onClose }) => {
  const [exportFormat, setExportFormat] = useState<'json' | 'csv'>('json');
  const [exportType, setExportType] = useState<'all' | 'METRIC' | 'ALERT' | 'ANALYSIS'>('all');
  const [dateRange, setDateRange] = useState({
    start: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    end: new Date().toISOString().split('T')[0]
  });
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const startDate = new Date(dateRange.start).toISOString();
      const endDate = new Date(dateRange.end + 'T23:59:59').toISOString();

      const data = dataLogger.exportData(exportFormat, exportType === 'all' ? undefined : exportType);

      // Create and download file
      const blob = new Blob([data], {
        type: exportFormat === 'json' ? 'application/json' : 'text/csv'
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `crowd-data-${exportType}-${dateRange.start}-to-${dateRange.end}.${exportFormat}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      // Log the export action
      dataLogger.logUserAction('Data export', {
        format: exportFormat,
        type: exportType,
        dateRange,
        timestamp: new Date().toISOString()
      });

      onClose();
    } catch (error) {
      console.error('Export failed:', error);
      dataLogger.logSystemEvent('Data export failed', { error: error.message });
    } finally {
      setIsExporting(false);
    }
  };

  const generateReport = () => {
    const startDate = new Date(dateRange.start).toISOString();
    const endDate = new Date(dateRange.end + 'T23:59:59').toISOString();

    const report = dataLogger.generateReport(startDate, endDate);

    // Create report content
    const reportContent = `
CROWD MANAGEMENT SYSTEM REPORT
Generated: ${new Date().toLocaleString()}

DATE RANGE: ${report.dateRange.start} to ${report.dateRange.end}

SUMMARY STATISTICS:
- Total Metrics Recorded: ${report.totalMetrics}
- Total Alerts Generated: ${report.totalAlerts}
- Peak Density Recorded: ${report.peakDensity.toFixed(2)} p/m²
- Average Risk Level: ${report.averageRiskLevel}

TOP ALERT LOCATIONS:
${report.topLocations.map(loc => `- ${loc.location}: ${loc.alerts} alerts`).join('\n')}

HOURLY TRENDS:
${report.hourlyTrends.map(hour => `${hour.hour.toString().padStart(2, '0')}:00 - Metrics: ${hour.metrics}, Alerts: ${hour.alerts}`).join('\n')}

RECOMMENDATIONS:
${report.averageRiskLevel === 'CRITICAL' ? '- Immediate intervention required' :
  report.averageRiskLevel === 'HIGH' ? '- Increased monitoring recommended' :
  report.averageRiskLevel === 'MEDIUM' ? '- Standard monitoring sufficient' :
  '- System operating normally'}

Generated by Project Drishti - Smart Crowd Management System
    `.trim();

    // Download report
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `crowd-report-${dateRange.start}-to-${dateRange.end}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    dataLogger.logUserAction('Report generated', {
      dateRange,
      timestamp: new Date().toISOString()
    });

    onClose();
  };

  const getPerformanceMetrics = () => {
    return dataLogger.getPerformanceMetrics();
  };

  const performance = getPerformanceMetrics();

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6 border-b border-slate-800">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold text-white">Data Export & Reports</h2>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white transition-colors"
            >
              <i className="fas fa-times text-xl"></i>
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {/* System Performance */}
          <div className="bg-slate-800/50 rounded-lg p-4">
            <h3 className="text-lg font-semibold text-white mb-3">System Performance</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
              <div>
                <span className="text-slate-400">Logs/Hour:</span>
                <span className="text-white ml-2">{performance.logsPerHour}</span>
              </div>
              <div>
                <span className="text-slate-400">Logs/Day:</span>
                <span className="text-white ml-2">{performance.logsPerDay}</span>
              </div>
              <div>
                <span className="text-slate-400">Storage:</span>
                <span className="text-white ml-2">{(performance.storageSize / 1024).toFixed(1)}KB</span>
              </div>
              <div>
                <span className="text-slate-400">Sessions:</span>
                <span className="text-white ml-2">{performance.sessionCount}</span>
              </div>
            </div>
          </div>

          {/* Export Settings */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-white">Export Settings</h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Format</label>
                <select
                  value={exportFormat}
                  onChange={(e) => setExportFormat(e.target.value as 'json' | 'csv')}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                >
                  <option value="json">JSON</option>
                  <option value="csv">CSV</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Data Type</label>
                <select
                  value={exportType}
                  onChange={(e) => setExportType(e.target.value as any)}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                >
                  <option value="all">All Data</option>
                  <option value="METRIC">Metrics Only</option>
                  <option value="ALERT">Alerts Only</option>
                  <option value="ANALYSIS">Analysis Only</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Start Date</label>
                <input
                  type="date"
                  value={dateRange.start}
                  onChange={(e) => setDateRange(prev => ({ ...prev, start: e.target.value }))}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">End Date</label>
                <input
                  type="date"
                  value={dateRange.end}
                  onChange={(e) => setDateRange(prev => ({ ...prev, end: e.target.value }))}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                />
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 pt-4 border-t border-slate-800">
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="flex-1 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center gap-2"
            >
              {isExporting ? (
                <>
                  <i className="fas fa-spinner fa-spin"></i>
                  Exporting...
                </>
              ) : (
                <>
                  <i className="fas fa-download"></i>
                  Export Data
                </>
              )}
            </button>

            <button
              onClick={generateReport}
              className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center gap-2"
            >
              <i className="fas fa-file-alt"></i>
              Generate Report
            </button>

            <button
              onClick={() => {
                dataLogger.clearOldData(7); // Clear data older than 7 days
                dataLogger.logUserAction('Data cleanup', { daysToKeep: 7 });
                onClose();
              }}
              className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center"
            >
              <i className="fas fa-trash"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DataExport;
